[build]
    publish = "public"
    functions = "functions"
    command = "# no build command"

[[redirects]]
    from = "/saved-banners/:text"
    to = "/.netlify/functions/svg-banner/:text"
    status = 200
    force = true
